services:
  backend:
    image: echx-backend:prod
    labels :
      - "traefik.enable=true"
      - "traefik.http.routers.api-echx.rule=Host(`api.echx.app`)"
      - "traefik.http.routers.api-echx.entrypoints=websecure"
      - "traefik.http.routers.api-echx.tls.certresolver=myresolver"
      - "traefik.http.services.api-echx.loadbalancer.server.port=8080"
    networks:
      - traefik

  frontend:
    image: echx-frontend:prod
    depends_on:
      - backend
    labels :
      - "traefik.enable=true"
      - "traefik.http.routers.echx.rule=Host(`echx.app`)"
      - "traefik.http.routers.echx.entrypoints=websecure"
      - "traefik.http.routers.echx.tls.certresolver=myresolver"
      - "traefik.http.services.echx.loadbalancer.server.port=80"
    networks:
      - traefik

networks:
  traefik:
    external: true
